.TH "Assignment2App" 3 "Thu Nov 20 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assignment2App
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignment2App\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file main\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assignment2App::Assignment2App ()\fC [inline]\fP"

.PP
Definition at line 14 of file main\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Assignment2App::run ()\fC [inline]\fP"

.PP
Definition at line 16 of file main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
