.TH "Assignment2App.h" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assignment2App.h
.SH SYNOPSIS
.br
.PP
\fC#include 'WeatherDataCollection\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssignment2App\fP"
.br
.RI "The main application class for Assignment 2, managing the user interface and data processing flow\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
