.TH "Assignment2App.cpp" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assignment2App.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Assignment2App\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <sstream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
