.TH "Bst.h" 3 "Thu Nov 20 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bst.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNode< T >\fP"
.br
.RI "Template node class for Binary Search Tree\&. "
.ti -1c
.RI "class \fBBst< T >\fP"
.br
.RI "Template Binary Search Tree with function pointers for traversal\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
