.TH "Bst< T >" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bst< T > \- Template Binary Search Tree with function pointers for traversal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bst\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBst\fP ()"
.br
.RI "Default constructor\&. Initializes an empty tree\&. "
.ti -1c
.RI "\fB~Bst\fP ()"
.br
.RI "Destructor\&. Cleans up the entire tree structure\&. "
.ti -1c
.RI "\fBBst\fP (const \fBBst\fP< T > &other)"
.br
.RI "Copy constructor\&. Performs a deep copy of the tree structure\&. "
.ti -1c
.RI "\fBBst\fP< T > & \fBoperator=\fP (const \fBBst\fP< T > &other)"
.br
.RI "Assignment operator\&. Handles self-assignment and performs a deep copy assignment\&. "
.ti -1c
.RI "void \fBinsert\fP (T *value)"
.br
.RI "Inserts a data value into the BST\&. Takes ownership of the pointer\&. "
.ti -1c
.RI "\fBNode\fP< T > * \fBsearch\fP (T *value) const"
.br
.RI "Searches for a data value in the BST\&. "
.ti -1c
.RI "void \fBinOrder\fP (void(*visit)(const T *)) const"
.br
.RI "Initiates an in-order traversal, applying the visit function to each node\&. "
.ti -1c
.RI "void \fBpreOrder\fP (void(*visit)(const T *)) const"
.br
.RI "Initiates a pre-order traversal, applying the visit function to each node\&. "
.ti -1c
.RI "void \fBpostOrder\fP (void(*visit)(const T *)) const"
.br
.RI "Initiates a post-order traversal, applying the visit function to each node\&. "
.ti -1c
.RI "void \fBinOrder\fP (void(*visit)(const T *, void *), void *context) const"
.br
.RI "Initiates an in-order traversal that uses a context pointer for collection\&. "
.ti -1c
.RI "void \fBinOrder\fP () const"
.br
.RI "Simple in-order traversal that prints the data (requires operator<< for T)\&. "
.ti -1c
.RI "void \fBpreOrder\fP () const"
.br
.RI "Simple pre-order traversal that prints the data (requires operator<< for T)\&. "
.ti -1c
.RI "void \fBpostOrder\fP () const"
.br
.RI "Simple post-order traversal that prints the data (requires operator<< for T)\&. "
.ti -1c
.RI "bool \fBcheckInvariant\fP () const"
.br
.RI "Checks if the tree satisfies the Binary Search Tree invariant\&. "
.ti -1c
.RI "bool \fBisEmpty\fP () const"
.br
.RI "Checks if the tree is empty\&. "
.ti -1c
.RI "int \fBsize\fP () const"
.br
.RI "Gets the total number of nodes in the tree\&. "
.ti -1c
.RI "int \fBheight\fP () const"
.br
.RI "Gets the height of the tree (number of edges on the longest path from the root to a leaf)\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class Bst< T >"
Template Binary Search Tree with function pointers for traversal\&. 
.PP
Definition at line 31 of file Bst\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBBst\fP< T >::\fBBst\fP"

.PP
Default constructor\&. Initializes an empty tree\&. Default constructor implementation\&. 
.PP
Definition at line 234 of file Bst\&.h\&.
.SS "template<class T > \fBBst\fP< T >::~\fBBst\fP"

.PP
Destructor\&. Cleans up the entire tree structure\&. Destructor implementation\&. Calls recursive delete function\&. 
.PP
Definition at line 240 of file Bst\&.h\&.
.SS "template<class T > \fBBst\fP< T >::\fBBst\fP (const \fBBst\fP< T > & other)"

.PP
Copy constructor\&. Performs a deep copy of the tree structure\&. Copy constructor implementation\&. Calls recursive copy function\&.
.PP
\fBParameters\fP
.RS 4
\fIother\fP The \fBBst\fP object to copy from\&. 
.RE
.PP

.PP
Definition at line 249 of file Bst\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > bool \fBBst\fP< T >::checkInvariant"

.PP
Checks if the tree satisfies the Binary Search Tree invariant\&. 
.PP
\fBReturns\fP
.RS 4
bool True if the invariant holds, false otherwise\&. 
.RE
.PP

.PP
Definition at line 506 of file Bst\&.h\&.
.SS "template<class T > int \fBBst\fP< T >::height"

.PP
Gets the height of the tree (number of edges on the longest path from the root to a leaf)\&. Gets the height of the tree\&.
.PP
\fBReturns\fP
.RS 4
int The height of the tree, or -1 if the tree is empty\&. 
.RE
.PP

.PP
Definition at line 559 of file Bst\&.h\&.
.SS "template<class T > void \fBBst\fP< T >::inOrder"

.PP
Simple in-order traversal that prints the data (requires operator<< for T)\&. 
.PP
Definition at line 456 of file Bst\&.h\&.
.SS "template<class T > void \fBBst\fP< T >::inOrder (void(*)(const T *) visit) const"

.PP
Initiates an in-order traversal, applying the visit function to each node\&. 
.PP
\fBParameters\fP
.RS 4
\fIvisit\fP The function pointer to apply to each node's data\&. 
.RE
.PP

.PP
Definition at line 375 of file Bst\&.h\&.
.SS "template<class T > void \fBBst\fP< T >::inOrder (void(*)(const T *, void *) visit, void * context) const"

.PP
Initiates an in-order traversal that uses a context pointer for collection\&. 
.PP
\fBParameters\fP
.RS 4
\fIvisit\fP The function pointer to apply (accepts data pointer and context pointer)\&. 
.br
\fIcontext\fP Opaque pointer to the context/collector struct\&. 
.RE
.PP

.PP
Definition at line 447 of file Bst\&.h\&.
.SS "template<class T > void \fBBst\fP< T >::insert (T * value)"

.PP
Inserts a data value into the BST\&. Takes ownership of the pointer\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The pointer to the data value to insert\&. 
.RE
.PP

.PP
Definition at line 322 of file Bst\&.h\&.
.SS "template<class T > bool \fBBst\fP< T >::isEmpty"

.PP
Checks if the tree is empty\&. 
.PP
\fBReturns\fP
.RS 4
bool True if the root is null\&. 
.RE
.PP

.PP
Definition at line 519 of file Bst\&.h\&.
.SS "template<class T > \fBBst\fP< T > & \fBBst\fP< T >::operator= (const \fBBst\fP< T > & other)"

.PP
Assignment operator\&. Handles self-assignment and performs a deep copy assignment\&. Assignment operator implementation\&. Handles cleanup and deep copy\&.
.PP
\fBParameters\fP
.RS 4
\fIother\fP The \fBBst\fP object to assign from\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bst<T>& Reference to the updated object\&. 
.RE
.PP

.PP
Definition at line 259 of file Bst\&.h\&.
.SS "template<class T > void \fBBst\fP< T >::postOrder"

.PP
Simple post-order traversal that prints the data (requires operator<< for T)\&. 
.PP
Definition at line 476 of file Bst\&.h\&.
.SS "template<class T > void \fBBst\fP< T >::postOrder (void(*)(const T *) visit) const"

.PP
Initiates a post-order traversal, applying the visit function to each node\&. 
.PP
\fBParameters\fP
.RS 4
\fIvisit\fP The function pointer to apply to each node's data\&. 
.RE
.PP

.PP
Definition at line 421 of file Bst\&.h\&.
.SS "template<class T > void \fBBst\fP< T >::preOrder"

.PP
Simple pre-order traversal that prints the data (requires operator<< for T)\&. 
.PP
Definition at line 466 of file Bst\&.h\&.
.SS "template<class T > void \fBBst\fP< T >::preOrder (void(*)(const T *) visit) const"

.PP
Initiates a pre-order traversal, applying the visit function to each node\&. 
.PP
\fBParameters\fP
.RS 4
\fIvisit\fP The function pointer to apply to each node's data\&. 
.RE
.PP

.PP
Definition at line 398 of file Bst\&.h\&.
.SS "template<class T > \fBNode\fP< T > * \fBBst\fP< T >::search (T * value) const"

.PP
Searches for a data value in the BST\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The pointer to the data value (used for comparison key)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Node<T>* The node containing the value, or nullptr if not found\&. 
.RE
.PP

.PP
Definition at line 351 of file Bst\&.h\&.
.SS "template<class T > int \fBBst\fP< T >::size"

.PP
Gets the total number of nodes in the tree\&. 
.PP
\fBReturns\fP
.RS 4
int The size of the tree\&. 
.RE
.PP

.PP
Definition at line 539 of file Bst\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
