.TH "CollectionContext" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollectionContext \- Context structure used during BST traversals to filter and collect records\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WeatherRecord\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBWeatherRecord\fP > * \fBrecords\fP"
.br
.ti -1c
.RI "int \fBtargetMonth\fP"
.br
.RI "The target month (1-12) used for filtering\&. "
.ti -1c
.RI "std::vector< \fBWeatherRecord\fP * > * \fBrecords\fP"
.br
.RI "Pointer to the vector where collected \fBWeatherRecord\fP pointers are stored\&. "
.ti -1c
.RI "int \fBtargetYear\fP"
.br
.RI "The target year used for filtering\&. "
.in -1c
.SH "Detailed Description"
.PP 
Context structure used during BST traversals to filter and collect records\&. 

This structure holds a pointer to a result vector and optional filtering criteria (target month and year)\&. 
.PP
Definition at line 266 of file WeatherData\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBWeatherRecord\fP*>* CollectionContext::records"

.PP
Pointer to the vector where collected \fBWeatherRecord\fP pointers are stored\&. 
.PP
Definition at line 114 of file WeatherRecord\&.h\&.
.SS "std::vector<\fBWeatherRecord\fP>* CollectionContext::records"

.PP
Definition at line 267 of file WeatherData\&.cpp\&.
.SS "int CollectionContext::targetMonth"

.PP
The target month (1-12) used for filtering\&. 
.PP
Definition at line 268 of file WeatherData\&.cpp\&.
.SS "int CollectionContext::targetYear"

.PP
The target year used for filtering\&. 
.PP
Definition at line 124 of file WeatherRecord\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
