.TH "CollectionContext" 3 "Thu Nov 20 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollectionContext
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBWeatherRecord\fP > * \fBrecords\fP"
.br
.ti -1c
.RI "int \fBtargetMonth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 266 of file WeatherData\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBWeatherRecord\fP>* CollectionContext::records"

.PP
Definition at line 267 of file WeatherData\&.cpp\&.
.SS "int CollectionContext::targetMonth"

.PP
Definition at line 268 of file WeatherData\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
