.TH "Date.h" 3 "Thu Nov 20 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Date.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBDate\fP &date)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBDate\fP &date)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, const \fBDate\fP & date)\fC [inline]\fP"

.PP
Definition at line 81 of file Date\&.h\&.
.SS "std::istream& operator>> (std::istream & is, \fBDate\fP & date)\fC [inline]\fP"

.PP
Definition at line 86 of file Date\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
