.TH "main.cpp" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Assignment2App\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Main function of the program\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Main function of the program\&. Creates an instance of the \fBAssignment2App\fP and starts the application loop\&.
.PP
\fBReturns\fP
.RS 4
int - Returns 0 upon successful execution\&. 
.RE
.PP

.PP
Definition at line 15 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
