.TH "Map< K, V >" 3 "Thu Nov 20 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map< K, V >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WeatherData\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMap\fP ()=default"
.br
.ti -1c
.RI "void \fBinsert\fP (const K &key, const V &value)"
.br
.ti -1c
.RI "bool \fBcontains\fP (const K &key) const"
.br
.ti -1c
.RI "V & \fBat\fP (const K &key)"
.br
.ti -1c
.RI "const V & \fBat\fP (const K &key) const"
.br
.ti -1c
.RI "std::map< K, V >::iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "std::map< K, V >::iterator \fBend\fP ()"
.br
.ti -1c
.RI "std::map< K, V >::const_iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "std::map< K, V >::const_iterator \fBend\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename K, typename V>
.br
class Map< K, V >"

.PP
Definition at line 17 of file WeatherData\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename K , typename V > \fBMap\fP< K, V >::\fBMap\fP ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename K , typename V > V& \fBMap\fP< K, V >::at (const K & key)\fC [inline]\fP"

.PP
Definition at line 33 of file WeatherData\&.h\&.
.SS "template<typename K , typename V > const V& \fBMap\fP< K, V >::at (const K & key) const\fC [inline]\fP"

.PP
Definition at line 37 of file WeatherData\&.h\&.
.SS "template<typename K , typename V > std::map<K, V>::iterator \fBMap\fP< K, V >::begin ()\fC [inline]\fP"

.PP
Definition at line 42 of file WeatherData\&.h\&.
.SS "template<typename K , typename V > std::map<K, V>::const_iterator \fBMap\fP< K, V >::begin () const\fC [inline]\fP"

.PP
Definition at line 44 of file WeatherData\&.h\&.
.SS "template<typename K , typename V > bool \fBMap\fP< K, V >::contains (const K & key) const\fC [inline]\fP"

.PP
Definition at line 29 of file WeatherData\&.h\&.
.SS "template<typename K , typename V > std::map<K, V>::iterator \fBMap\fP< K, V >::end ()\fC [inline]\fP"

.PP
Definition at line 43 of file WeatherData\&.h\&.
.SS "template<typename K , typename V > std::map<K, V>::const_iterator \fBMap\fP< K, V >::end () const\fC [inline]\fP"

.PP
Definition at line 45 of file WeatherData\&.h\&.
.SS "template<typename K , typename V > void \fBMap\fP< K, V >::insert (const K & key, const V & value)\fC [inline]\fP"

.PP
Definition at line 25 of file WeatherData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
