.TH "Map.h" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map.h
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMap< K, V >\fP"
.br
.RI "A template wrapper class for the standard C++ std::map container\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
