.TH "ModelFile::TemplateObject" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelFile::TemplateObject \- Defines a single model used in a template\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ModelFile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "XYZ \fBpos\fP"
.br
.RI "Position of model\&. "
.ti -1c
.RI "float \fBangle\fP"
.br
.RI "Rotation angle\&. "
.ti -1c
.RI "BlockModel * \fBmodel\fP"
.br
.RI "Pointer to model\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a single model used in a template\&. 
.PP
Definition at line 152 of file ModelFile\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float ModelFile::TemplateObject::angle"

.PP
Rotation angle\&. 
.PP
Definition at line 157 of file ModelFile\&.h\&.
.SS "BlockModel* ModelFile::TemplateObject::model"

.PP
Pointer to model\&. 
.PP
Definition at line 159 of file ModelFile\&.h\&.
.SS "XYZ ModelFile::TemplateObject::pos"

.PP
Position of model\&. 
.PP
Definition at line 155 of file ModelFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
