.TH "ModelFile.h" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelFile.h
.SH SYNOPSIS
.br
.PP
\fC#include 'BlockModel\&.h'\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModelFile\fP"
.br
.RI "Manages all models and room templates\&. "
.ti -1c
.RI "struct \fBModelFile::TemplateObject\fP"
.br
.RI "Defines a single model used in a template\&. "
.ti -1c
.RI "struct \fBModelFile::Template\fP"
.br
.RI "Defines a single room template\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
