.TH "ModelFile::Template" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelFile::Template \- Defines a single room template\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ModelFile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.RI "Name of template\&. "
.ti -1c
.RI "vector< \fBTemplateObject\fP > \fBobjects\fP"
.br
.RI "Vector of models and their positions/rotations\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a single room template\&. 
.PP
Definition at line 163 of file ModelFile\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "string ModelFile::Template::name"

.PP
Name of template\&. 
.PP
Definition at line 166 of file ModelFile\&.h\&.
.SS "vector<\fBTemplateObject\fP> ModelFile::Template::objects"

.PP
Vector of models and their positions/rotations\&. 
.PP
Definition at line 168 of file ModelFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
