.TH "Node< T >" 3 "Thu Nov 20 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node< T > \- Template node class for Binary Search Tree\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bst\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (const T &value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBdata\fP"
.br
.ti -1c
.RI "\fBNode\fP< T > * \fBleft\fP"
.br
.ti -1c
.RI "\fBNode\fP< T > * \fBright\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class Node< T >"
Template node class for Binary Search Tree\&. 
.PP
Definition at line 10 of file Bst\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBNode\fP< T >::\fBNode\fP (const T & value)\fC [inline]\fP"

.PP
Definition at line 16 of file Bst\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T > T \fBNode\fP< T >::data"

.PP
Definition at line 12 of file Bst\&.h\&.
.SS "template<class T > \fBNode\fP<T>* \fBNode\fP< T >::left"

.PP
Definition at line 13 of file Bst\&.h\&.
.SS "template<class T > \fBNode\fP<T>* \fBNode\fP< T >::right"

.PP
Definition at line 14 of file Bst\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
