.TH "Node< T >" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node< T > \- Template node class for Binary Search Tree\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bst\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (T *value)"
.br
.RI "Constructs a \fBNode\fP, taking ownership of the provided data pointer\&. "
.ti -1c
.RI "\fB~Node\fP ()"
.br
.RI "Destructor\&. Deletes the owned data element\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T * \fBdata\fP"
.br
.RI "Store pointer to the data element\&. "
.ti -1c
.RI "\fBNode\fP< T > * \fBleft\fP"
.br
.RI "Pointer to the left child node\&. "
.ti -1c
.RI "\fBNode\fP< T > * \fBright\fP"
.br
.RI "Pointer to the right child node\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class Node< T >"
Template node class for Binary Search Tree\&. 
.PP
Definition at line 10 of file Bst\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBNode\fP< T >::\fBNode\fP (T * value)\fC [inline]\fP"

.PP
Constructs a \fBNode\fP, taking ownership of the provided data pointer\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The pointer to the data element\&. 
.RE
.PP

.PP
Definition at line 20 of file Bst\&.h\&.
.SS "template<class T > \fBNode\fP< T >::~\fBNode\fP ()\fC [inline]\fP"

.PP
Destructor\&. Deletes the owned data element\&. 
.PP
Definition at line 25 of file Bst\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T > T* \fBNode\fP< T >::data"

.PP
Store pointer to the data element\&. 
.PP
Definition at line 12 of file Bst\&.h\&.
.SS "template<class T > \fBNode\fP<T>* \fBNode\fP< T >::left"

.PP
Pointer to the left child node\&. 
.PP
Definition at line 13 of file Bst\&.h\&.
.SS "template<class T > \fBNode\fP<T>* \fBNode\fP< T >::right"

.PP
Pointer to the right child node\&. 
.PP
Definition at line 14 of file Bst\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
