.TH "Statistics.cpp" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Statistics.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Statistics\&.h'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBStatistics\fP"
.br
.RI "Namespace for statistical calculations using pointer-based vectors\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBStatistics::calculateMean\fP (const std::vector< double > *values)"
.br
.RI "Calculates the arithmetic mean (average) of a set of values\&. "
.ti -1c
.RI "double \fBStatistics::calculateStdDev\fP (const std::vector< double > *values)"
.br
.RI "Calculates the Sample Standard Deviation of a set of values\&. "
.ti -1c
.RI "double \fBStatistics::calculateMAD\fP (const std::vector< double > *values)"
.br
.RI "Calculates the Mean Absolute Deviation (MAD) of a set of values\&. "
.ti -1c
.RI "double \fBStatistics::calculateSPCC\fP (const std::vector< double > *x, const std::vector< double > *y)"
.br
.RI "Calculates the Sample Pearson Correlation Coefficient (SPCC) between two datasets\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
