.TH "Statistics" 3 "Thu Nov 20 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Statistics
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBcalculateMean\fP (const std::vector< double > &values)"
.br
.ti -1c
.RI "double \fBcalculateStdDev\fP (const std::vector< double > &values)"
.br
.ti -1c
.RI "double \fBcalculateMAD\fP (const std::vector< double > &values)"
.br
.ti -1c
.RI "double \fBcalculateSPCC\fP (const std::vector< double > &x, const std::vector< double > &y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double Statistics::calculateMAD (const std::vector< double > & values)"

.PP
Definition at line 359 of file WeatherData\&.cpp\&.
.SS "double Statistics::calculateMean (const std::vector< double > & values)"

.PP
Definition at line 331 of file WeatherData\&.cpp\&.
.SS "double Statistics::calculateSPCC (const std::vector< double > & x, const std::vector< double > & y)"

.PP
Definition at line 374 of file WeatherData\&.cpp\&.
.SS "double Statistics::calculateStdDev (const std::vector< double > & values)"

.PP
Definition at line 344 of file WeatherData\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
