.TH "todo" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBClass \fBAssignment2App\fP \fP" 1c
Implement input validation for all user prompts (e\&.g\&., check for non-numeric input)\&. 
.PP
Separate the UI logic from the data processing logic further for better modularity\&.  
.IP "\fBClass \fBModelFile\fP \fP" 1c
Let Harry know his block class is being used\&.
.PP

