.TH "WeatherDataCollection.cpp" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WeatherDataCollection.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'WeatherDataCollection\&.h'\fP
.br
\fC#include 'Statistics\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <numeric>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <random>\fP
.br
\fC#include <chrono>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
