.TH "WeatherDataCollection.h" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WeatherDataCollection.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Bst\&.h'\fP
.br
\fC#include 'Map\&.h'\fP
.br
\fC#include 'WeatherRecord\&.h'\fP
.br
\fC#include 'Statistics\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWeatherDataCollection\fP"
.br
.RI "Collection of weather data with BST storage and month mapping\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
