.TH "WeatherData.h" 3 "Sun Nov 23 2025" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WeatherData.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Date\&.h'\fP
.br
\fC#include 'Bst\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMap< K, V >\fP"
.br
.RI "A template wrapper class for the standard C++ std::map container\&. "
.ti -1c
.RI "class \fBWeatherRecord\fP"
.br
.RI "Represents a single weather data observation at a specific date and time\&. "
.ti -1c
.RI "class \fBWeatherDataCollection\fP"
.br
.RI "Collection of weather data with BST storage and month mapping\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBStatistics\fP"
.br
.RI "Namespace for statistical calculations using pointer-based vectors\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBStatistics::calculateMean\fP (const std::vector< double > &values)"
.br
.ti -1c
.RI "double \fBStatistics::calculateStdDev\fP (const std::vector< double > &values)"
.br
.ti -1c
.RI "double \fBStatistics::calculateMAD\fP (const std::vector< double > &values)"
.br
.ti -1c
.RI "double \fBStatistics::calculateSPCC\fP (const std::vector< double > &x, const std::vector< double > &y)"
.br
.ti -1c
.RI "void \fBprintWeatherRecord\fP (const \fBWeatherRecord\fP &record)"
.br
.ti -1c
.RI "void \fBcollectByMonth\fP (const \fBWeatherRecord\fP &record, void *context)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void collectByMonth (const \fBWeatherRecord\fP & record, void * context)"

.PP
Definition at line 271 of file WeatherData\&.cpp\&.
.SS "void printWeatherRecord (const \fBWeatherRecord\fP & record)"

.PP
Definition at line 262 of file WeatherData\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
