DoxyExample: Map< K, V > Class Template Reference
Map< K, V > Class Template Reference
A template wrapper class for the standard C++ std::map container.
#include <Map.h>
Public Member Functions
Map ()
Default constructor.
~Map ()
Destructor.
Map (const Map &other)
Copy constructor (Rule of Three).
Map & operator= (const Map &other)
Assignment operator (Rule of Three).
void insert (const K *key, const V *value)
Inserts a key-value pair into the map.
bool contains (const K *key) const
Checks if the map contains the specified key.
V * at (const K *key)
Retrieves a pointer to the value associated with the specified key (mutable version).
const V * at (const K *key) const
Retrieves a constant pointer to the value associated with the specified key (constant version).
size_t size () const
Returns the number of key-value pairs in the map.
std::map< K, V >::iterator begin ()
Returns an iterator pointing to the first element in the map (mutable).
std::map< K, V >::iterator end ()
Returns an iterator referring to the past-the-end element in the map (mutable).
std::map< K, V >::const_iterator begin () const
Returns a const iterator pointing to the first element in the map (constant).
std::map< K, V >::const_iterator end () const
Returns a const iterator referring to the past-the-end element in the map (constant).
Map ()=default
void insert (const K &key, const V &value)
bool contains (const K &key) const
V & at (const K &key)
const V & at (const K &key) const
std::map< K, V >::iterator begin ()
std::map< K, V >::iterator end ()
std::map< K, V >::const_iterator begin () const
std::map< K, V >::const_iterator end () const
Private Attributes
std::map< K, V > * internalMap
Pointer to the internal standard C++ map container.
std::map< K, V > internalMap
Detailed Description
template<typename K, typename V>
class Map< K, V >
A template wrapper class for the standard C++ std::map container.
This class provides a dynamic, heap-allocated wrapper around std::map, implementing the Rule of Three (Destructor, Copy Constructor, Assignment Operator) and providing specific methods for insertion and retrieval that handle key and value pointers, as required by the application's design.
Template Parameters
K The type of the key (must be comparable).
V The type of the value.
Definition at line 19 of file Map.h.
Constructor & Destructor Documentation
Map() [1/3]
template<typename K , typename V > Map< K, V >::Map () inline
Default constructor.
Initializes and dynamically allocates the internal std::map.
Definition at line 32 of file Map.h.
~Map()
template<typename K , typename V > Map< K, V >::~Map () inline
Destructor.
Frees the dynamically allocated internal std::map.
Definition at line 41 of file Map.h.
Map() [2/3]
template<typename K , typename V > Map< K, V >::Map (const Map< K, V > & other) inline
Copy constructor (Rule of Three).
Performs a deep copy of the internal map from the 'other' Map object.
Parameters
other The Map object to copy from.
Definition at line 51 of file Map.h.
Map() [3/3]
template<typename K , typename V > Map< K, V >::Map () default
Member Function Documentation
at() [1/4]
template<typename K , typename V > V& Map< K, V >::at (const K & key) inline
Definition at line 33 of file WeatherData.h.
at() [2/4]
template<typename K , typename V > const V& Map< K, V >::at (const K & key) const inline
Definition at line 37 of file WeatherData.h.
at() [3/4]
template<typename K , typename V > V* Map< K, V >::at (const K * key) inline
Retrieves a pointer to the value associated with the specified key (mutable version).
Behaves like std::map operator[]: if the key does not exist, it is inserted with a default-constructed value.
Parameters
key A constant pointer to the key.
Returns
V* A mutable pointer to the value.
Definition at line 100 of file Map.h.
Referenced by WeatherDataCollection::addWeatherRecord(), WeatherDataCollection::getDataForMonth(), and WeatherDataCollection::getDataForYearMonth().
at() [4/4]
template<typename K , typename V > const V* Map< K, V >::at (const K * key) const inline
Retrieves a constant pointer to the value associated with the specified key (constant version).
Behaves like std::map::at(): throws an exception if the key is not found.
Parameters
key A constant pointer to the key.
Returns
const V* A constant pointer to the value.
Definition at line 111 of file Map.h.
begin() [1/4]
template<typename K , typename V > std::map<K, V>::iterator Map< K, V >::begin () inline
Definition at line 42 of file WeatherData.h.
begin() [2/4]
template<typename K , typename V > std::map<K, V>::iterator Map< K, V >::begin () inline
Returns an iterator pointing to the first element in the map (mutable).
Returns
typename std::map<K, V>::iterator An iterator to the beginning.
Definition at line 126 of file Map.h.
begin() [3/4]
template<typename K , typename V > std::map<K, V>::const_iterator Map< K, V >::begin () const inline
Definition at line 44 of file WeatherData.h.
begin() [4/4]
template<typename K , typename V > std::map<K, V>::const_iterator Map< K, V >::begin () const inline
Returns a const iterator pointing to the first element in the map (constant).
Returns
typename std::map<K, V>::const_iterator A const iterator to the beginning.
Definition at line 138 of file Map.h.
contains() [1/2]
template<typename K , typename V > bool Map< K, V >::contains (const K & key) const inline
Definition at line 29 of file WeatherData.h.
contains() [2/2]
template<typename K , typename V > bool Map< K, V >::contains (const K * key) const inline
Checks if the map contains the specified key.
Parameters
key A constant pointer to the key to search for.
Returns
bool True if the key is found, false otherwise.
Definition at line 88 of file Map.h.
Referenced by WeatherDataCollection::addWeatherRecord(), and WeatherDataCollection::monthExists().
end() [1/4]
template<typename K , typename V > std::map<K, V>::iterator Map< K, V >::end () inline
Definition at line 43 of file WeatherData.h.
end() [2/4]
template<typename K , typename V > std::map<K, V>::iterator Map< K, V >::end () inline
Returns an iterator referring to the past-the-end element in the map (mutable).
Returns
typename std::map<K, V>::iterator An iterator to the end.
Definition at line 132 of file Map.h.
end() [3/4]
template<typename K , typename V > std::map<K, V>::const_iterator Map< K, V >::end () const inline
Definition at line 45 of file WeatherData.h.
end() [4/4]
template<typename K , typename V > std::map<K, V>::const_iterator Map< K, V >::end () const inline
Returns a const iterator referring to the past-the-end element in the map (constant).
Returns
typename std::map<K, V>::const_iterator A const iterator to the end.
Definition at line 144 of file Map.h.
insert() [1/2]
template<typename K , typename V > void Map< K, V >::insert (const K & key, const V & value) inline
Definition at line 25 of file WeatherData.h.
insert() [2/2]
template<typename K , typename V > void Map< K, V >::insert (const K * key, const V * value) inline
Inserts a key-value pair into the map.
Keys and values are passed as pointers, but the dereferenced copies are stored in the internal map (copy semantics).
Parameters
key A constant pointer to the key to insert.
value A constant pointer to the value to insert.
Definition at line 79 of file Map.h.
Referenced by WeatherDataCollection::addWeatherRecord().
operator=()
template<typename K , typename V > Map& Map< K, V >::operator= (const Map< K, V > & other) inline
Assignment operator (Rule of Three).
Performs a deep copy assignment. Cleans up existing resources and copies the internal map from the 'other' Map object.
Parameters
other The Map object to assign from.
Returns
Map& A reference to the current Map object.
Definition at line 63 of file Map.h.
size()
template<typename K , typename V > size_t Map< K, V >::size () const inline
Returns the number of key-value pairs in the map.
Returns
size_t The size of the map.
Definition at line 119 of file Map.h.
Member Data Documentation
internalMap [1/2]
template<typename K , typename V > std::map<K, V> Map< K, V >::internalMap private
Definition at line 19 of file WeatherData.h.
internalMap [2/2]
template<typename K , typename V > std::map<K, V>* Map< K, V >::internalMap private
Pointer to the internal standard C++ map container.
Definition at line 24 of file Map.h.
Referenced by Map< int, std::vector< WeatherRecord * > >::at(), Map< int, std::vector< WeatherRecord * > >::begin(), Map< int, std::vector< WeatherRecord * > >::contains(), Map< int, std::vector< WeatherRecord * > >::end(), Map< int, std::vector< WeatherRecord * > >::insert(), Map< int, std::vector< WeatherRecord * > >::Map(), Map< int, std::vector< WeatherRecord * > >::operator=(), Map< int, std::vector< WeatherRecord * > >::size(), and Map< int, std::vector< WeatherRecord * > >::~Map().
The documentation for this class was generated from the following files:
Map.h
WeatherData.h