DoxyExample: Bst< T > Class Template Reference
Bst< T > Class Template Reference
Template Binary Search Tree with function pointers for traversal.
#include <Bst.h>
Public Member Functions
Bst ()
Default constructor. Initializes an empty tree.
~Bst ()
Destructor. Cleans up the entire tree structure.
Bst (const Bst< T > &other)
Copy constructor. Performs a deep copy of the tree structure.
Bst< T > & operator= (const Bst< T > &other)
Assignment operator. Handles self-assignment and performs a deep copy assignment.
void insert (T *value)
Inserts a data value into the BST. Takes ownership of the pointer.
Node< T > * search (T *value) const
Searches for a data value in the BST.
void inOrder (void(*visit)(const T *)) const
Initiates an in-order traversal, applying the visit function to each node.
void preOrder (void(*visit)(const T *)) const
Initiates a pre-order traversal, applying the visit function to each node.
void postOrder (void(*visit)(const T *)) const
Initiates a post-order traversal, applying the visit function to each node.
void inOrder (void(*visit)(const T *, void *), void *context) const
Initiates an in-order traversal that uses a context pointer for collection.
void inOrder () const
Simple in-order traversal that prints the data (requires operator<< for T).
void preOrder () const
Simple pre-order traversal that prints the data (requires operator<< for T).
void postOrder () const
Simple post-order traversal that prints the data (requires operator<< for T).
bool checkInvariant () const
Checks if the tree satisfies the Binary Search Tree invariant.
bool isEmpty () const
Checks if the tree is empty.
int size () const
Gets the total number of nodes in the tree.
int height () const
Gets the height of the tree (number of edges on the longest path from the root to a leaf).
Private Member Functions
Node< T > * insertRec (Node< T > *node, T *value)
Recursively inserts a new node containing the value.
Node< T > * searchRec (Node< T > *node, T *value) const
Recursively searches for a node containing the value.
void inOrderRec (Node< T > *node, void(*visit)(const T *)) const
Performs recursive in-order traversal and applies the visit function.
void preOrderRec (Node< T > *node, void(*visit)(const T *)) const
Performs recursive pre-order traversal and applies the visit function.
void postOrderRec (Node< T > *node, void(*visit)(const T *)) const
Performs recursive post-order traversal and applies the visit function.
void inOrderRec (Node< T > *node, void(*visit)(const T *, void *), void *context) const
Performs recursive in-order traversal, applying the visit function with a context pointer.
void deleteTreeRec (Node< T > *node)
Recursively deletes all nodes in the tree, cleaning up memory.
bool checkInvariantRec (Node< T > *node, const T *min, const T *max) const
Recursively checks the Binary Search Tree invariant.
Node< T > * copyTreeRec (Node< T > *node)
Recursively creates a deep copy of the tree structure.
int sizeRec (Node< T > *node) const
Recursively calculates the size of the subtree rooted at node.
int heightRec (Node< T > *node) const
Recursively calculates the height of the subtree rooted at node.
Private Attributes
Node< T > * root
Pointer to the root node of the tree.
Detailed Description
template<class T>
class Bst< T >
Template Binary Search Tree with function pointers for traversal.
Definition at line 31 of file Bst.h.
Constructor & Destructor Documentation
Bst() [1/2]
template<class T > Bst< T >::Bst
Default constructor. Initializes an empty tree.
Default constructor implementation.
Definition at line 234 of file Bst.h.
~Bst()
template<class T > Bst< T >::~Bst
Destructor. Cleans up the entire tree structure.
Destructor implementation. Calls recursive delete function.
Definition at line 240 of file Bst.h.
Bst() [2/2]
template<class T > Bst< T >::Bst (const Bst< T > & other)
Copy constructor. Performs a deep copy of the tree structure.
Copy constructor implementation. Calls recursive copy function.
Parameters
other The Bst object to copy from.
Definition at line 249 of file Bst.h.
Member Function Documentation
checkInvariant()
template<class T > bool Bst< T >::checkInvariant
Checks if the tree satisfies the Binary Search Tree invariant.
Returns
bool True if the invariant holds, false otherwise.
Definition at line 506 of file Bst.h.
checkInvariantRec()
template<class T > bool Bst< T >::checkInvariantRec (Node< T > * node, const T * min, const T * max) const private
Recursively checks the Binary Search Tree invariant.
Parameters
node The current node being checked.
min A pointer to the minimum allowed value for the subtree.
max A pointer to the maximum allowed value for the subtree.
Returns
bool True if the invariant holds, false otherwise.
Definition at line 490 of file Bst.h.
copyTreeRec()
template<class T > Node< T > * Bst< T >::copyTreeRec (Node< T > * node) private
Recursively creates a deep copy of the tree structure.
Parameters
node The root of the tree/subtree to copy.
Returns
Node<T>* The root of the newly copied tree/subtree.
Definition at line 273 of file Bst.h.
Referenced by Bst< WeatherRecord >::Bst().
deleteTreeRec()
template<class T > void Bst< T >::deleteTreeRec (Node< T > * node) private
Recursively deletes all nodes in the tree, cleaning up memory.
Parameters
node The current node to delete (and its children).
Definition at line 289 of file Bst.h.
height()
template<class T > int Bst< T >::height
Gets the height of the tree (number of edges on the longest path from the root to a leaf).
Gets the height of the tree.
Returns
int The height of the tree, or -1 if the tree is empty.
Definition at line 559 of file Bst.h.
heightRec()
template<class T > int Bst< T >::heightRec (Node< T > * node) const private
Recursively calculates the height of the subtree rooted at node.
Parameters
node The root of the subtree.
Returns
int The height of the subtree.
Definition at line 549 of file Bst.h.
inOrder() [1/3]
template<class T > void Bst< T >::inOrder
Simple in-order traversal that prints the data (requires operator<< for T).
Definition at line 456 of file Bst.h.
inOrder() [2/3]
template<class T > void Bst< T >::inOrder (void(*)(const T *) visit) const
Initiates an in-order traversal, applying the visit function to each node.
Parameters
visit The function pointer to apply to each node's data.
Definition at line 375 of file Bst.h.
Referenced by WeatherDataCollection::displayAllData(), WeatherDataCollection::getDataForMonth(), WeatherDataCollection::getDataForSpecificMonthYear(), and WeatherDataCollection::getDataForYearMonth().
inOrder() [3/3]
template<class T > void Bst< T >::inOrder (void(*)(const T *, void *) visit, void * context) const
Initiates an in-order traversal that uses a context pointer for collection.
Parameters
visit The function pointer to apply (accepts data pointer and context pointer).
context Opaque pointer to the context/collector struct.
Definition at line 447 of file Bst.h.
inOrderRec() [1/2]
template<class T > void Bst< T >::inOrderRec (Node< T > * node, void(*)(const T *) visit) const private
Performs recursive in-order traversal and applies the visit function.
Parameters
node The current node being examined.
visit The function pointer to apply to each node's data.
Definition at line 362 of file Bst.h.
inOrderRec() [2/2]
template<class T > void Bst< T >::inOrderRec (Node< T > * node, void(*)(const T *, void *) visit, void * context) const private
Performs recursive in-order traversal, applying the visit function with a context pointer.
This is typically used for collection logic where data is stored in the context struct.
Parameters
node The current node being examined.
visit The function pointer to apply (accepts data pointer and context pointer).
context Opaque pointer to the context/collector struct.
node The current node being examined.
visit The function pointer to apply (accepts data pointer and context pointer).
context Opaque pointer to the context/collector struct.
Definition at line 433 of file Bst.h.
insert()
template<class T > void Bst< T >::insert (T * value)
Inserts a data value into the BST. Takes ownership of the pointer.
Parameters
value The pointer to the data value to insert.
Definition at line 322 of file Bst.h.
Referenced by WeatherDataCollection::addWeatherRecord().
insertRec()
template<class T > Node< T > * Bst< T >::insertRec (Node< T > * node, T * value) private
Recursively inserts a new node containing the value.
Parameters
node The current node being examined.
value The pointer to the data value to insert.
Returns
Node<T>* The updated root of the subtree.
Definition at line 304 of file Bst.h.
isEmpty()
template<class T > bool Bst< T >::isEmpty
Checks if the tree is empty.
Returns
bool True if the root is null.
Definition at line 519 of file Bst.h.
operator=()
template<class T > Bst< T > & Bst< T >::operator= (const Bst< T > & other)
Assignment operator. Handles self-assignment and performs a deep copy assignment.
Assignment operator implementation. Handles cleanup and deep copy.
Parameters
other The Bst object to assign from.
Returns
Bst<T>& Reference to the updated object.
Definition at line 259 of file Bst.h.
postOrder() [1/2]
template<class T > void Bst< T >::postOrder
Simple post-order traversal that prints the data (requires operator<< for T).
Definition at line 476 of file Bst.h.
postOrder() [2/2]
template<class T > void Bst< T >::postOrder (void(*)(const T *) visit) const
Initiates a post-order traversal, applying the visit function to each node.
Parameters
visit The function pointer to apply to each node's data.
Definition at line 421 of file Bst.h.
postOrderRec()
template<class T > void Bst< T >::postOrderRec (Node< T > * node, void(*)(const T *) visit) const private
Performs recursive post-order traversal and applies the visit function.
Parameters
node The current node being examined.
visit The function pointer to apply to each node's data.
Definition at line 408 of file Bst.h.
preOrder() [1/2]
template<class T > void Bst< T >::preOrder
Simple pre-order traversal that prints the data (requires operator<< for T).
Definition at line 466 of file Bst.h.
preOrder() [2/2]
template<class T > void Bst< T >::preOrder (void(*)(const T *) visit) const
Initiates a pre-order traversal, applying the visit function to each node.
Parameters
visit The function pointer to apply to each node's data.
Definition at line 398 of file Bst.h.
preOrderRec()
template<class T > void Bst< T >::preOrderRec (Node< T > * node, void(*)(const T *) visit) const private
Performs recursive pre-order traversal and applies the visit function.
Parameters
node The current node being examined.
visit The function pointer to apply to each node's data.
Definition at line 385 of file Bst.h.
search()
template<class T > Node< T > * Bst< T >::search (T * value) const
Searches for a data value in the BST.
Parameters
value The pointer to the data value (used for comparison key).
Returns
Node<T>* The node containing the value, or nullptr if not found.
Definition at line 351 of file Bst.h.
searchRec()
template<class T > Node< T > * Bst< T >::searchRec (Node< T > * node, T * value) const private
Recursively searches for a node containing the value.
Parameters
node The current node being examined.
value The pointer to the data value to search for.
Returns
Node<T>* The node containing the value, or nullptr if not found.
Definition at line 333 of file Bst.h.
size()
template<class T > int Bst< T >::size
Gets the total number of nodes in the tree.
Returns
int The size of the tree.
Definition at line 539 of file Bst.h.
Referenced by WeatherDataCollection::getTotalRecords().
sizeRec()
template<class T > int Bst< T >::sizeRec (Node< T > * node) const private
Recursively calculates the size of the subtree rooted at node.
Parameters
node The root of the subtree.
Returns
int The size of the subtree.
Definition at line 529 of file Bst.h.
Member Data Documentation
root
template<class T > Node<T>* Bst< T >::root private
Pointer to the root node of the tree.
Definition at line 33 of file Bst.h.
Referenced by Bst< WeatherRecord >::Bst(), and Bst< WeatherRecord >::operator=().
The documentation for this class was generated from the following file:
Bst.h