DoxyExample: Assignment2App Class Reference
Assignment2App Class Reference
The main application class for Assignment 2, managing the user interface and data processing flow.
#include <Assignment2App.h>
Public Member Functions
Assignment2App ()
Constructor for the Assignment2App class.
void run ()
Runs the main application loop.
Private Member Functions
void displayMenu ()
Displays the main application menu to the console.
void processChoice (int choice)
Processes the user's choice from the menu.
void loadData ()
Handles the loading of weather data from the user-specified file.
void displayData ()
Displays all loaded weather data records.
void displayAverageWindSpeed ()
Calculates and displays the average wind speed and standard deviation for a specific year and month.
void displayMonthlyTemperatures ()
Displays the monthly temperature averages and standard deviations for a specified year.
void calculateCorrelations ()
Calculates and displays Pearson Correlation Coefficients for the specified month across all years.
void generateReport ()
Generates a monthly statistics report file for a specified year.
Private Attributes
WeatherDataCollection weatherData
An instance of the WeatherDataCollection class to hold and process all weather records.
bool dataLoaded
Flag to indicate whether weather data has been successfully loaded from files.
Detailed Description
The main application class for Assignment 2, managing the user interface and data processing flow.
This class handles the main menu loop, user input, and delegates data-related tasks to the WeatherDataCollection object. It ensures data is loaded before analysis options are offered.
Author
[Your Name Here]
Version
01
Date
23/11/2025 Started
Todo:
Implement input validation for all user prompts (e.g., check for non-numeric input).
Separate the UI logic from the data processing logic further for better modularity.
Definition at line 34 of file Assignment2App.h.
Constructor & Destructor Documentation
Assignment2App()
Assignment2App::Assignment2App ()
Constructor for the Assignment2App class.
Initializes the WeatherDataCollection object and sets the dataLoaded flag to false.
Returns
void
Definition at line 23 of file Assignment2App.cpp.
Member Function Documentation
calculateCorrelations()
void Assignment2App::calculateCorrelations () private
Calculates and displays Pearson Correlation Coefficients for the specified month across all years.
Prompts for the month, calculates S_T, S_R, and T_R correlation coefficients, and displays the results. Checks if data is loaded first.
Returns
void
Definition at line 193 of file Assignment2App.cpp.
References WeatherDataCollection::calculateSPCC(), dataLoaded, and weatherData.
Referenced by processChoice().
displayAverageWindSpeed()
void Assignment2App::displayAverageWindSpeed () private
Calculates and displays the average wind speed and standard deviation for a specific year and month.
Prompts for year and month, then calls weatherData.displayAverageWindSpeed(). Checks if data is loaded first.
Returns
void
Definition at line 151 of file Assignment2App.cpp.
References dataLoaded, WeatherDataCollection::displayAverageWindSpeed(), and weatherData.
Referenced by processChoice().
displayData()
void Assignment2App::displayData () private
Displays all loaded weather data records.
Calls weatherData.displayAllData(). Checks if data is loaded first.
Returns
void
Definition at line 135 of file Assignment2App.cpp.
References dataLoaded, WeatherDataCollection::displayAllData(), and weatherData.
Referenced by processChoice().
displayMenu()
void Assignment2App::displayMenu () private
Displays the main application menu to the console.
Returns
void
Definition at line 54 of file Assignment2App.cpp.
Referenced by run().
displayMonthlyTemperatures()
void Assignment2App::displayMonthlyTemperatures () private
Displays the monthly temperature averages and standard deviations for a specified year.
Prompts for the year, then calls weatherData.displayMonthlyTemperatures(). Checks if data is loaded first.
Returns
void
Definition at line 173 of file Assignment2App.cpp.
References dataLoaded, WeatherDataCollection::displayMonthlyTemperatures(), and weatherData.
Referenced by processChoice().
generateReport()
void Assignment2App::generateReport () private
Generates a monthly statistics report file for a specified year.
Prompts for the year, then calls weatherData.generateMonthlyStats() to create a CSV file. Checks if data is loaded first.
Returns
void
Definition at line 237 of file Assignment2App.cpp.
References dataLoaded, WeatherDataCollection::generateMonthlyStats(), and weatherData.
Referenced by processChoice().
loadData()
void Assignment2App::loadData () private
Handles the loading of weather data from the user-specified file.
Prompts the user for a filename, loads the data into weatherData, and sets dataLoaded to true.
Returns
void
Definition at line 117 of file Assignment2App.cpp.
References dataLoaded, WeatherDataCollection::loadFromFiles(), and weatherData.
Referenced by processChoice().
processChoice()
void Assignment2App::processChoice (int choice) private
Processes the user's choice from the menu.
Calls the appropriate member function based on the menu choice.
Parameters
choice - The integer value corresponding to the menu option selected by the user.
Returns
void
Definition at line 75 of file Assignment2App.cpp.
References calculateCorrelations(), displayAverageWindSpeed(), displayData(), displayMonthlyTemperatures(), generateReport(), and loadData().
Referenced by run().
run()
void Assignment2App::run ()
Runs the main application loop.
Displays the menu, takes user input, and processes the selected choice until the exit option (7) is chosen.
Returns
void
Definition at line 37 of file Assignment2App.cpp.
References displayMenu(), and processChoice().
Referenced by main().
Member Data Documentation
dataLoaded
bool Assignment2App::dataLoaded private
Flag to indicate whether weather data has been successfully loaded from files.
Definition at line 62 of file Assignment2App.h.
Referenced by calculateCorrelations(), displayAverageWindSpeed(), displayData(), displayMonthlyTemperatures(), generateReport(), and loadData().
weatherData
WeatherDataCollection Assignment2App::weatherData private
An instance of the WeatherDataCollection class to hold and process all weather records.
Definition at line 59 of file Assignment2App.h.
Referenced by calculateCorrelations(), displayAverageWindSpeed(), displayData(), displayMonthlyTemperatures(), generateReport(), and loadData().
The documentation for this class was generated from the following files:
Assignment2App.h
Assignment2App.cpp