DoxyExample: WeatherDataCollection Class Reference
WeatherDataCollection Class Reference
Collection of weather data with BST storage and month mapping.
#include <WeatherData.h>
Public Member Functions
WeatherDataCollection ()
Default constructor for WeatherDataCollection.
~WeatherDataCollection ()
Destructor for WeatherDataCollection.
void addWeatherRecord (const WeatherRecord &record)
void loadFromFiles (const std::string &dataSourceFile)
std::vector< WeatherRecord > getDataForMonth (int month) const
Get data for Month only.
std::vector< WeatherRecord > getDataForYearMonth (int year, int month) const
std::vector< WeatherRecord > getDataForSpecificMonthYear (int year, int month) const
double calculateSPCC (int month, const std::string &correlationType) const
Calculation of SPCC.
void displayAverageWindSpeed (int year, int month) const
New Menu option tasked from assignment 2.
void displayMonthlyTemperatures (int year) const
Menu option 3: Average ambient air temperature and sample standard deviation for each month of a specified year.
void generateMonthlyStats (int year, const std::string &filename) const
void displayAllData () const
Displays all stored weather data records to the console in order.
int getTotalRecords () const
Returns the total number of weather records stored in the collection.
std::vector< int > getAvailableYears () const
WeatherDataCollection ()
Default constructor.
~WeatherDataCollection ()
Destructor.
WeatherDataCollection (const WeatherDataCollection &other)
Copy constructor (Rule of Three).
WeatherDataCollection & operator= (const WeatherDataCollection &other)
Assignment operator (Rule of Three).
void addWeatherRecord (WeatherRecord *record)
Adds a single weather record to the collection.
void loadFromFiles (std::string *filename)
Loads weather data from a file specified by the filename.
std::vector< WeatherRecord * > * getDataForMonth (int *month) const
Retrieves a vector of pointers to all records for a given month, across all years.
std::vector< WeatherRecord * > * getDataForYearMonth (int *year, int *month) const
Retrieves a vector of pointers to records for a specific year and month.
std::vector< WeatherRecord * > * getDataForSpecificMonthYear (int *year, int *month) const
Retrieves a vector of pointers to records for a specific year and month (alternative function name).
double calculateSPCC (int *year, int *month, std::string *type) const
Calculates the Sample Pearson Correlation Coefficient (SPCC) for data points of a specific year and month, based on the correlation type requested.
void displayAverageWindSpeed (int *year, int *month) const
Displays the average wind speed and its standard deviation for a given year and month.
void displayMonthlyTemperatures (int *year) const
Displays the average and standard deviation of temperature for each month of a given year.
void generateMonthlyStats (int *year, std::string *filename) const
Generates and writes a comprehensive monthly statistics report to a file.
void displayAllData () const
Displays all weather data records stored in the collection (typically using an inorder traversal of the BST).
int getTotalRecords () const
Returns the total number of weather records stored in the collection.
Private Member Functions
void parseAndAddRecord (const std::string &line)
Date parseDate (const std::string &dateTimeString)
bool monthExists (int month) const
void parseAndAddRecord (std::string *line)
Internal helper function to parse a single line of raw data and create a WeatherRecord.
Date * parseDate (std::string *dateTimeString)
Internal helper function to parse a date/time string into a Date object.
Static Private Member Functions
static double calculateMean (const std::vector< double > &values)
static double calculateStdDev (const std::vector< double > &values)
static double calculateMAD (const std::vector< double > &values)
Private Attributes
Bst< WeatherRecord > weatherDataBST
Map< int, std::vector< WeatherRecord * > > dataByMonth
Bst< WeatherRecord > * weatherDataBST
Binary search tree containing all WeatherRecord objects, ordered by date.
Map< int, std::vector< WeatherRecord * > > * dataByMonth
Map where the key is the month (1-12) and the value is a vector of pointers to WeatherRecord objects that occurred in that month.
Detailed Description
Collection of weather data with BST storage and month mapping.
This class manages weather data records, storing them in a Binary Search Tree (BST) sorted by date, and additionally maintaining a map for quick access by month. It provides functionality for loading data, performing statistical calculations, and generating reports.
Definition at line 67 of file WeatherData.h.
Constructor & Destructor Documentation
WeatherDataCollection() [1/3]
WeatherDataCollection::WeatherDataCollection ()
Default constructor for WeatherDataCollection.
Initializes the Binary Search Tree (BST) and the Map used for monthly lookups.
Returns
void
Definition at line 33 of file WeatherData.cpp.
~WeatherDataCollection() [1/2]
WeatherDataCollection::~WeatherDataCollection ()
Destructor for WeatherDataCollection.
Deletes the dynamically allocated BST and Map structures. The BST is assumed to handle the deletion of the contained WeatherRecord objects and their associated Date objects.
Returns
void
Definition at line 36 of file WeatherData.cpp.
WeatherDataCollection() [2/3]
WeatherDataCollection::WeatherDataCollection ()
Default constructor.
Initializes the internal BST and Map structures.
~WeatherDataCollection() [2/2]
WeatherDataCollection::~WeatherDataCollection ()
Destructor.
Cleans up and deletes dynamically allocated memory for the BST and Map.
WeatherDataCollection() [3/3]
WeatherDataCollection::WeatherDataCollection (const WeatherDataCollection & other)
Copy constructor (Rule of Three).
Copy constructor for WeatherDataCollection.
Parameters
other The WeatherDataCollection object to copy from.
Performs a deep copy of the BST and the monthly lookup Map.
Parameters
other - The WeatherDataCollection object to copy from.
Returns
void
Definition at line 62 of file WeatherDataCollection.cpp.
Member Function Documentation
addWeatherRecord() [1/2]
void WeatherDataCollection::addWeatherRecord (const WeatherRecord & record)
Definition at line 39 of file WeatherData.cpp.
References Map< K, V >::at(), Map< K, V >::contains(), dataByMonth, WeatherRecord::date, Date::GetMonth(), Map< K, V >::insert(), Bst< T >::insert(), and weatherDataBST.
Referenced by loadFromFiles(), and parseAndAddRecord().
addWeatherRecord() [2/2]
void WeatherDataCollection::addWeatherRecord (WeatherRecord * record)
Adds a single weather record to the collection.
Adds a new WeatherRecord to the collection.
Inserts the record into the BST and updates the dataByMonth map.
Parameters
record A pointer to the WeatherRecord to add.
Inserts the record into the BST for ordered storage and also adds its pointer to the corresponding monthly vector in the Map for fast lookup.
Parameters
record - Pointer to the WeatherRecord to be added. Ownership remains with this class.
Returns
void
Definition at line 93 of file WeatherDataCollection.cpp.
References Map< K, V >::at(), Map< K, V >::contains(), dataByMonth, WeatherRecord::date, Date::GetMonth(), Map< K, V >::insert(), Bst< T >::insert(), and weatherDataBST.
calculateMAD()
static double WeatherDataCollection::calculateMAD (const std::vector< double > & values) static private
calculateMean()
static double WeatherDataCollection::calculateMean (const std::vector< double > & values) static private
calculateSPCC() [1/2]
double WeatherDataCollection::calculateSPCC (int * year, int * month, std::string * type) const
Calculates the Sample Pearson Correlation Coefficient (SPCC) for data points of a specific year and month, based on the correlation type requested.
Calculates the Sample Pearson Correlation Coefficient (SPCC) between two variables for a given month and year.
Parameters
year A constant pointer to the integer representing the year (or sentinel for all years).
month A constant pointer to the integer representing the month (1-12).
type A constant pointer to the string indicating the correlation type (e.g., "S_T", "S_R", "T_R").
Returns
double The calculated SPCC value.
Supports calculation across all years for a given month if year is 0. The correlation type (S_T, S_R, T_R) specifies the variables to compare.
Parameters
year - Pointer to the target year (0 for all years).
month - Pointer to the target month (1-12).
type - Pointer to the string defining the correlation type ("S_T", "S_R", "T_R").
Returns
double - The calculated SPCC value, or 0.0 if data is insufficient or input is invalid.
Definition at line 346 of file WeatherDataCollection.cpp.
References Statistics::calculateSPCC(), getDataForMonth(), and getDataForSpecificMonthYear().
calculateSPCC() [2/2]
double WeatherDataCollection::calculateSPCC (int month, const std::string & correlationType) const
Calculation of SPCC.
Definition at line 279 of file WeatherData.cpp.
References Statistics::calculateSPCC(), and getDataForMonth().
Referenced by Assignment2App::calculateCorrelations().
calculateStdDev()
static double WeatherDataCollection::calculateStdDev (const std::vector< double > & values) static private
displayAllData() [1/2]
void WeatherDataCollection::displayAllData () const
Displays all stored weather data records to the console in order.
Performs an in-order traversal on the BST and prints each record.
Returns
void
Definition at line 461 of file WeatherData.cpp.
References getTotalRecords(), Bst< T >::inOrder(), and weatherDataBST.
Referenced by Assignment2App::displayData().
displayAllData() [2/2]
void WeatherDataCollection::displayAllData () const
Displays all weather data records stored in the collection (typically using an inorder traversal of the BST).
displayAverageWindSpeed() [1/2]
void WeatherDataCollection::displayAverageWindSpeed (int * year, int * month) const
Displays the average wind speed and its standard deviation for a given year and month.
Calculates and displays the average wind speed and standard deviation for a specific year and month.
Parameters
year A constant pointer to the integer representing the year.
month A constant pointer to the integer representing the month (1-12).
Retrieves the relevant data and uses the Statistics module for calculation and console output.
Parameters
year - Pointer to the target year.
month - Pointer to the target month (1-12).
Returns
void
Definition at line 409 of file WeatherDataCollection.cpp.
References Statistics::calculateMean(), Statistics::calculateStdDev(), and getDataForYearMonth().
displayAverageWindSpeed() [2/2]
void WeatherDataCollection::displayAverageWindSpeed (int year, int month) const
New Menu option tasked from assignment 2.
Menu Option 2: The average wind speed and sample standard deviation for this wind speed given a specified month and year
Definition at line 192 of file WeatherData.cpp.
References Statistics::calculateMean(), Statistics::calculateStdDev(), and getDataForSpecificMonthYear().
Referenced by Assignment2App::displayAverageWindSpeed().
displayMonthlyTemperatures() [1/2]
void WeatherDataCollection::displayMonthlyTemperatures (int * year) const
Displays the average and standard deviation of temperature for each month of a given year.
Displays the monthly temperature averages, standard deviations, and MADs for a specified year.
Parameters
year A constant pointer to the integer representing the year.
Iterates through all 12 months, retrieves data, performs statistical calculations, and outputs the results.
Parameters
year - Pointer to the target year.
Returns
void
Definition at line 440 of file WeatherDataCollection.cpp.
References Statistics::calculateMean(), Statistics::calculateStdDev(), and getDataForYearMonth().
displayMonthlyTemperatures() [2/2]
void WeatherDataCollection::displayMonthlyTemperatures (int year) const
Menu option 3: Average ambient air temperature and sample standard deviation for each month of a specified year.
Definition at line 216 of file WeatherData.cpp.
References Statistics::calculateMean(), Statistics::calculateStdDev(), and getDataForSpecificMonthYear().
Referenced by Assignment2App::displayMonthlyTemperatures().
generateMonthlyStats() [1/2]
void WeatherDataCollection::generateMonthlyStats (int * year, std::string * filename) const
Generates and writes a comprehensive monthly statistics report to a file.
Generates a CSV file containing monthly statistics for wind speed, temperature, and solar radiation for a specified year.
Parameters
year A constant pointer to the integer representing the year.
filename A constant pointer to the output filename string.
Calculates mean, standard deviation, and Mean Absolute Deviation (MAD) for wind and temperature, and total solar radiation for each month.
Parameters
year - Pointer to the target year.
filename - Pointer to the output filename (e.g., "WindTempSolar.csv").
Returns
void
Definition at line 479 of file WeatherDataCollection.cpp.
References Statistics::calculateMAD(), Statistics::calculateMean(), Statistics::calculateStdDev(), and getDataForYearMonth().
generateMonthlyStats() [2/2]
void WeatherDataCollection::generateMonthlyStats (int year, const std::string & filename) const
Definition at line 404 of file WeatherData.cpp.
References Statistics::calculateMAD(), Statistics::calculateMean(), Statistics::calculateStdDev(), and getDataForYearMonth().
Referenced by Assignment2App::generateReport().
getAvailableYears()
std::vector<int> WeatherDataCollection::getAvailableYears () const
getDataForMonth() [1/2]
std::vector< WeatherRecord * > * WeatherDataCollection::getDataForMonth (int * month) const
Retrieves a vector of pointers to all records for a given month, across all years.
Retrieves all weather records for a specific month across all years.
Parameters
month A constant pointer to the integer representing the month (1-12).
Returns
std::vector<WeatherRecord*>* A pointer to the vector of records, or null if month is invalid/no data.
Performs a traversal of the BST to collect all records matching the month, regardless of year. The year parameter in the internal context is set to 0 to indicate all years.
Parameters
month - Pointer to the target month (1-12).
Returns
std::vector<WeatherRecord*>* - Pointer to a new vector containing deep copies of the records, or nullptr if month is invalid. Caller must delete the vector and its contents.
Definition at line 295 of file WeatherDataCollection.cpp.
References collectByMonth(), Bst< T >::inOrder(), CollectionContext::records, and weatherDataBST.
getDataForMonth() [2/2]
std::vector< WeatherRecord > WeatherDataCollection::getDataForMonth (int month) const
Get data for Month only.
Definition at line 245 of file WeatherData.cpp.
References Map< K, V >::at(), dataByMonth, and monthExists().
Referenced by calculateSPCC().
getDataForSpecificMonthYear() [1/2]
std::vector< WeatherRecord * > * WeatherDataCollection::getDataForSpecificMonthYear (int * year, int * month) const
Retrieves a vector of pointers to records for a specific year and month (alternative function name).
Retrieves all weather records for a specific year and month.
Parameters
year A constant pointer to the integer representing the year.
month A constant pointer to the integer representing the month (1-12).
Returns
std::vector<WeatherRecord*>* A pointer to the vector of records.
This helper is specifically designed to use the collectByYearMonth traversal function. The returned vector contains deep copies of the records.
Parameters
year - Pointer to the target year.
month - Pointer to the target month (1-12).
Returns
std::vector<WeatherRecord*>* - Pointer to a new vector containing deep copies of the records, or nullptr if input is invalid. Caller must delete the vector and its contents.
Definition at line 320 of file WeatherDataCollection.cpp.
References collectByYearMonth(), Bst< T >::inOrder(), CollectionContext::records, and weatherDataBST.
getDataForSpecificMonthYear() [2/2]
std::vector< WeatherRecord > WeatherDataCollection::getDataForSpecificMonthYear (int year, int month) const
Definition at line 323 of file WeatherData.cpp.
References getDataForYearMonth().
Referenced by calculateSPCC(), displayAverageWindSpeed(), and displayMonthlyTemperatures().
getDataForYearMonth() [1/2]
std::vector< WeatherRecord * > * WeatherDataCollection::getDataForYearMonth (int * year, int * month) const
Retrieves a vector of pointers to records for a specific year and month.
Retrieves all weather records for a specific year and month.
Parameters
year A constant pointer to the integer representing the year.
month A constant pointer to the integer representing the month (1-12).
Returns
std::vector<WeatherRecord*>* A pointer to the vector of records.
Note
This is typically implemented by iterating through the month data and filtering by year.
Performs a traversal of the BST to collect matching records. Note: The returned vector contains deep copies of the records to isolate them from the main collection.
Parameters
year - Pointer to the target year (e.g., 2010).
month - Pointer to the target month (1-12).
Returns
std::vector<WeatherRecord*>* - Pointer to a new vector containing deep copies of the records, or an empty vector if none are found. Caller must delete the vector and its contents.
Definition at line 278 of file WeatherDataCollection.cpp.
References collectByYearMonth(), Bst< T >::inOrder(), and weatherDataBST.
getDataForYearMonth() [2/2]
std::vector< WeatherRecord > WeatherDataCollection::getDataForYearMonth (int year, int month) const
Definition at line 304 of file WeatherData.cpp.
References Map< K, V >::at(), dataByMonth, and monthExists().
Referenced by displayAverageWindSpeed(), displayMonthlyTemperatures(), generateMonthlyStats(), and getDataForSpecificMonthYear().
getTotalRecords() [1/2]
int WeatherDataCollection::getTotalRecords () const
Returns the total number of weather records stored in the collection.
Calls the size() method of the internal BST.
Returns
int - The total number of records.
Definition at line 469 of file WeatherData.cpp.
References Bst< T >::size(), and weatherDataBST.
Referenced by displayAllData(), and loadFromFiles().
getTotalRecords() [2/2]
int WeatherDataCollection::getTotalRecords () const
Returns the total number of weather records stored in the collection.
Returns
int The count of records.
loadFromFiles() [1/2]
void WeatherDataCollection::loadFromFiles (const std::string & dataSourceFile)
Definition at line 63 of file WeatherData.cpp.
References parseAndAddRecord().
Referenced by Assignment2App::loadData().
loadFromFiles() [2/2]
void WeatherDataCollection::loadFromFiles (std::string * filename)
Loads weather data from a file specified by the filename.
Loads weather data from a list of CSV files.
Reads, parses, and adds each record to the collection.
Parameters
filename A constant pointer to the string containing the path to the data file.
Reads filenames from the provided list file, then parses each CSV, creates WeatherRecord objects, and adds them to the collection. Records are shuffled before final insertion into the BST for balance.
Parameters
filename - Pointer to the string containing the name of the file listing the CSVs.
Returns
void
Definition at line 136 of file WeatherDataCollection.cpp.
References addWeatherRecord(), getTotalRecords(), and parseDate().
monthExists()
bool WeatherDataCollection::monthExists (int month) const private
Definition at line 58 of file WeatherData.cpp.
References Map< K, V >::contains(), and dataByMonth.
Referenced by getDataForMonth(), and getDataForYearMonth().
operator=()
WeatherDataCollection & WeatherDataCollection::operator= (const WeatherDataCollection & other)
Assignment operator (Rule of Three).
Assignment operator for WeatherDataCollection.
Parameters
other The WeatherDataCollection object to assign from.
Returns
WeatherDataCollection& A reference to the current object.
Cleans up existing resources and performs a deep copy assignment.
Parameters
other - The WeatherDataCollection object to assign from.
Returns
WeatherDataCollection& - Reference to the updated object.
Definition at line 74 of file WeatherDataCollection.cpp.
References dataByMonth, and weatherDataBST.
parseAndAddRecord() [1/2]
void WeatherDataCollection::parseAndAddRecord (const std::string & line) private
Definition at line 122 of file WeatherData.cpp.
References addWeatherRecord(), and parseDate().
Referenced by loadFromFiles().
parseAndAddRecord() [2/2]
void WeatherDataCollection::parseAndAddRecord (std::string * line) private
Internal helper function to parse a single line of raw data and create a WeatherRecord.
Parameters
line A pointer to the raw data string line.
parseDate() [1/2]
Date WeatherDataCollection::parseDate (const std::string & dateTimeString) private
Definition at line 164 of file WeatherData.cpp.
Referenced by loadFromFiles(), and parseAndAddRecord().
parseDate() [2/2]
Date * WeatherDataCollection::parseDate (std::string * dateTimeString) private
Internal helper function to parse a date/time string into a Date object.
Parses a combined date and time string into a Date object.
Parameters
dateTimeString A pointer to the raw date/time string.
Returns
Date* A pointer to the newly created Date object.
Handles the format "D/MM/YYYY H:MM" and returns a dynamically allocated Date object. Returns a default Date if parsing fails.
Parameters
dateTimeString - Pointer to the string containing the date and time.
Returns
Date* - Pointer to the newly created Date object.
Definition at line 236 of file WeatherDataCollection.cpp.
Member Data Documentation
dataByMonth [1/2]
Map<int, std::vector<WeatherRecord*> >* WeatherDataCollection::dataByMonth private
Map where the key is the month (1-12) and the value is a vector of pointers to WeatherRecord objects that occurred in that month.
Map of month to records
Definition at line 31 of file WeatherDataCollection.h.
dataByMonth [2/2]
Map<int, std::vector<WeatherRecord*> > WeatherDataCollection::dataByMonth private
Definition at line 70 of file WeatherData.h.
Referenced by addWeatherRecord(), getDataForMonth(), getDataForYearMonth(), monthExists(), and operator=().
weatherDataBST [1/2]
Bst<WeatherRecord>* WeatherDataCollection::weatherDataBST private
Binary search tree containing all WeatherRecord objects, ordered by date.
Binary search tree of all records
Definition at line 25 of file WeatherDataCollection.h.
weatherDataBST [2/2]
Bst<WeatherRecord> WeatherDataCollection::weatherDataBST private
Definition at line 69 of file WeatherData.h.
Referenced by addWeatherRecord(), displayAllData(), getDataForMonth(), getDataForSpecificMonthYear(), getDataForYearMonth(), getTotalRecords(), and operator=().
The documentation for this class was generated from the following files:
WeatherData.h
WeatherDataCollection.h
WeatherData.cpp
WeatherDataCollection.cpp