DoxyExample: Statistics Namespace Reference
Statistics Namespace Reference
Namespace for statistical calculations using pointer-based vectors.
Functions
double calculateMean (const std::vector< double > *values)
Calculates the arithmetic mean (average) of a set of values.
double calculateStdDev (const std::vector< double > *values)
Calculates the Sample Standard Deviation of a set of values.
double calculateMAD (const std::vector< double > *values)
Calculates the Mean Absolute Deviation (MAD) of a set of values.
double calculateSPCC (const std::vector< double > *x, const std::vector< double > *y)
Calculates the Sample Pearson Correlation Coefficient (SPCC) between two datasets.
double calculateMean (const std::vector< double > &values)
double calculateStdDev (const std::vector< double > &values)
double calculateMAD (const std::vector< double > &values)
double calculateSPCC (const std::vector< double > &x, const std::vector< double > &y)
Detailed Description
Namespace for statistical calculations using pointer-based vectors.
This namespace provides several static functions for common statistical calculations, specifically designed to accept constant pointers to standard C++ vectors of doubles.
Function Documentation
calculateMAD() [1/2]
double Statistics::calculateMAD (const std::vector< double > & values)
Definition at line 359 of file WeatherData.cpp.
References calculateMean().
calculateMAD() [2/2]
double Statistics::calculateMAD (const std::vector< double > * values)
Calculates the Mean Absolute Deviation (MAD) of a set of values.
Calculates the Median Absolute Deviation (MAD) of a set of values.
The average of the absolute differences between each value and the mean.
Parameters
values - Pointer to the vector of double values.
Returns
double - The calculated MAD, or 0.0 if the vector is empty.
Note: The actual median calculation must be handled within the implementation.
Parameters
values A constant pointer to the vector of double values.
Returns
double The calculated Median Absolute Deviation.
Definition at line 52 of file Statistics.cpp.
References calculateMean().
Referenced by WeatherDataCollection::generateMonthlyStats().
calculateMean() [1/2]
double Statistics::calculateMean (const std::vector< double > & values)
Definition at line 331 of file WeatherData.cpp.
calculateMean() [2/2]
double Statistics::calculateMean (const std::vector< double > * values)
Calculates the arithmetic mean (average) of a set of values.
Parameters
values - Pointer to the vector of double values.
Returns
double - The calculated mean, or 0.0 if the vector is empty.
Parameters
values A constant pointer to the vector of double values.
Returns
double The calculated mean. Returns 0.0 if the vector is empty.
Definition at line 17 of file Statistics.cpp.
Referenced by calculateMAD(), calculateStdDev(), WeatherDataCollection::displayAverageWindSpeed(), WeatherDataCollection::displayMonthlyTemperatures(), and WeatherDataCollection::generateMonthlyStats().
calculateSPCC() [1/2]
double Statistics::calculateSPCC (const std::vector< double > & x, const std::vector< double > & y)
Definition at line 374 of file WeatherData.cpp.
calculateSPCC() [2/2]
double Statistics::calculateSPCC (const std::vector< double > * x, const std::vector< double > * y)
Calculates the Sample Pearson Correlation Coefficient (SPCC) between two datasets.
Calculates the Sample Pearson Correlation Coefficient (SPCC) between two data sets.
Parameters
x - Pointer to the first vector (independent variable).
y - Pointer to the second vector (dependent variable).
Returns
double - The calculated SPCC (range [-1, 1]), or 0.0 if datasets are too small or unequal size.
Parameters
x A constant pointer to the vector of double values for the X variable.
y A constant pointer to the vector of double values for the Y variable.
Returns
double The calculated SPCC. Returns 0.0 if the vectors are not the same size or size < 2.
Definition at line 69 of file Statistics.cpp.
Referenced by WeatherDataCollection::calculateSPCC().
calculateStdDev() [1/2]
double Statistics::calculateStdDev (const std::vector< double > & values)
Definition at line 344 of file WeatherData.cpp.
References calculateMean().
calculateStdDev() [2/2]
double Statistics::calculateStdDev (const std::vector< double > * values)
Calculates the Sample Standard Deviation of a set of values.
Calculates the sample standard deviation of a set of values.
Uses the N-1 method (Bessel's correction).
Parameters
values - Pointer to the vector of double values.
Returns
double - The calculated standard deviation, or 0.0 if there is less than two values.
Parameters
values A constant pointer to the vector of double values.
Returns
double The calculated standard deviation. Returns 0.0 if size < 2.
Definition at line 34 of file Statistics.cpp.
References calculateMean().
Referenced by WeatherDataCollection::displayAverageWindSpeed(), WeatherDataCollection::displayMonthlyTemperatures(), and WeatherDataCollection::generateMonthlyStats().