DoxyExample: WeatherRecord.h File Reference
WeatherRecord.h File Reference
#include "Date.h"
#include <vector>
#include <iostream>
Classes
class WeatherRecord
Represents a single weather data observation at a specific date and time.
struct CollectionContext
Context structure used during BST traversals to filter and collect records.
Functions
void printWeatherRecord (const WeatherRecord *record)
Utility function to print the details of a WeatherRecord.
void collectByMonth (const WeatherRecord *record, void *context)
Traversal helper function to collect records based only on the target month.
void collectByYearMonth (const WeatherRecord *record, void *context)
Traversal helper function to collect records based on both the target year and month.
std::ostream & operator<< (std::ostream &os, const WeatherRecord *wr)
Overloads the stream insertion operator to print a WeatherRecord pointer.
Function Documentation
collectByMonth()
void collectByMonth (const WeatherRecord * record, void * context)
Traversal helper function to collect records based only on the target month.
Designed to be passed to a BST traversal function.
Parameters
record A constant pointer to the current WeatherRecord during traversal.
context A void pointer to a CollectionContext structure.
Traversal helper function to collect records based only on the target month.
If the record's month matches the context's target month, a deep copy of the record is added to the context vector. This function is designed to be used by the BST's inOrder traversal.
Parameters
record - Pointer to the current WeatherRecord during traversal.
context - Pointer to the CollectionContext struct containing the target month and the results vector.
Returns
void
Definition at line 129 of file WeatherRecord.cpp.
References WeatherRecord::date, Date::GetMonth(), CollectionContext::records, and CollectionContext::targetMonth.
collectByYearMonth()
void collectByYearMonth (const WeatherRecord * record, void * context)
Traversal helper function to collect records based on both the target year and month.
Designed to be passed to a BST traversal function.
Parameters
record A constant pointer to the current WeatherRecord during traversal.
context A void pointer to a CollectionContext structure.
Traversal helper function to collect records based on both the target year and month.
If the record's year and month match the context's target, a deep copy of the record is added to the context vector. This function is designed to be used by the BST's inOrder traversal.
Parameters
record - Pointer to the current WeatherRecord during traversal.
context - Pointer to the CollectionContext struct containing the target year/month and the results vector.
Returns
void
Definition at line 146 of file WeatherRecord.cpp.
References WeatherRecord::date, Date::GetMonth(), Date::GetYear(), CollectionContext::records, CollectionContext::targetMonth, and CollectionContext::targetYear.
Referenced by WeatherDataCollection::getDataForSpecificMonthYear(), and WeatherDataCollection::getDataForYearMonth().
operator<<()
std::ostream& operator<< (std::ostream & os, const WeatherRecord * wr)
Overloads the stream insertion operator to print a WeatherRecord pointer.
Outputs the record's details to the output stream.
Parameters
os The output stream.
wr A constant pointer to the WeatherRecord to print.
Returns
std::ostream& Reference to the output stream.
Overloads the stream insertion operator to print a WeatherRecord pointer.
Provides a convenient way to output WeatherRecord data to an output stream.
Parameters
os - The output stream.
wr - Pointer to the WeatherRecord object to output.
Returns
std::ostream& - Reference to the output stream.
Definition at line 162 of file WeatherRecord.cpp.
References WeatherRecord::date, WeatherRecord::solarRadiation, WeatherRecord::temperature, and WeatherRecord::windSpeed.
printWeatherRecord()
void printWeatherRecord (const WeatherRecord * record)
Utility function to print the details of a WeatherRecord.
Designed to be used as a function pointer argument in BST traversals.
Parameters
record A constant pointer to the WeatherRecord to be printed.
Utility function to print the details of a WeatherRecord.
Prints the details of a single weather record to standard output.
Parameters
record - Pointer to the WeatherRecord to be printed.
Returns
void
Definition at line 113 of file WeatherRecord.cpp.
References WeatherRecord::date, WeatherRecord::solarRadiation, WeatherRecord::temperature, and WeatherRecord::windSpeed.